-- Generated by Drizzle; append-only trigger below is reviewed hand-written SQL.
CREATE TABLE "enrollment_lifecycle_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence" integer GENERATED ALWAYS AS IDENTITY (sequence name "enrollment_lifecycle_records_sequence_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"enrollment_id" uuid NOT NULL,
	"learning_path_version_id" uuid NOT NULL,
	"actor_account_id" uuid NOT NULL,
	"learner_account_id" uuid NOT NULL,
	"action" text NOT NULL,
	"reason" text,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "enrollment_lifecycle_records_sequence_key" UNIQUE("sequence"),
	CONSTRAINT "enrollment_lifecycle_records_action" CHECK ("enrollment_lifecycle_records"."action" IN ('deactivate', 'reactivate')),
	CONSTRAINT "enrollment_lifecycle_records_reason" CHECK (("enrollment_lifecycle_records"."reason" IS NOT NULL AND length(trim("enrollment_lifecycle_records"."reason")) > 0 AND length("enrollment_lifecycle_records"."reason") <= 500) OR ("enrollment_lifecycle_records"."reason" IS NULL AND "enrollment_lifecycle_records"."action" = 'deactivate' AND "enrollment_lifecycle_records"."actor_account_id" = "enrollment_lifecycle_records"."learner_account_id"))
);
--> statement-breakpoint
ALTER TABLE "enrollment_lifecycle_records" ADD CONSTRAINT "enrollment_lifecycle_records_actor_account_id_accounts_id_fk" FOREIGN KEY ("actor_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrollment_lifecycle_records" ADD CONSTRAINT "enrollment_lifecycle_records_learner_account_id_accounts_id_fk" FOREIGN KEY ("learner_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "enrollment_lifecycle_records" ADD CONSTRAINT "enrollment_lifecycle_records_enrollment_id_learning_path_version_id_enrollments_id_learning_path_version_id_fk" FOREIGN KEY ("enrollment_id","learning_path_version_id") REFERENCES "public"."enrollments"("id","learning_path_version_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE FUNCTION protect_enrollment_lifecycle_record() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Enrollment lifecycle records are immutable';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER enrollment_lifecycle_records_immutable BEFORE UPDATE OR DELETE ON enrollment_lifecycle_records
FOR EACH ROW EXECUTE FUNCTION protect_enrollment_lifecycle_record();