-- Generated by Drizzle, reordered so referenced UNIQUE constraints precede their FKs; append-only triggers below are reviewed hand-written SQL.
CREATE TABLE "personal_mastery_events" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "personal_mastery_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"learning_path_id" uuid NOT NULL,
	"skill_id" uuid NOT NULL,
	"actor_account_id" uuid NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"action" text NOT NULL,
	CONSTRAINT "personal_mastery_events_action" CHECK ("personal_mastery_events"."action" IN ('declare', 'withdraw'))
);
--> statement-breakpoint
CREATE TABLE "personal_override_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"sequence" integer GENERATED ALWAYS AS IDENTITY (sequence name "personal_override_records_sequence_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"learning_path_id" uuid NOT NULL,
	"skill_id" uuid NOT NULL,
	"actor_account_id" uuid NOT NULL,
	"action" text NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	CONSTRAINT "personal_override_records_sequence_key" UNIQUE("sequence"),
	CONSTRAINT "personal_override_records_action" CHECK ("personal_override_records"."action" IN ('grant', 'revoke'))
);
--> statement-breakpoint
CREATE TABLE "personal_prerequisites" (
	"learning_path_id" uuid NOT NULL,
	"prerequisite_skill_id" uuid NOT NULL,
	"skill_id" uuid NOT NULL,
	CONSTRAINT "personal_prerequisites_pk" PRIMARY KEY("learning_path_id","prerequisite_skill_id","skill_id"),
	CONSTRAINT "personal_prerequisites_no_self_edge" CHECK ("personal_prerequisites"."prerequisite_skill_id" <> "personal_prerequisites"."skill_id")
);
--> statement-breakpoint
CREATE TABLE "personal_skills" (
	"skill_id" uuid PRIMARY KEY NOT NULL,
	"learning_path_id" uuid NOT NULL,
	"personal_workspace_id" uuid NOT NULL,
	"title" text NOT NULL,
	"learning_outcome" text NOT NULL,
	"xp_threshold" integer DEFAULT 0 NOT NULL,
	"mastery_declared_at" timestamp with time zone,
	CONSTRAINT "personal_skills_path_skill_key" UNIQUE("learning_path_id","skill_id"),
	CONSTRAINT "personal_skills_xp_threshold_nonnegative" CHECK ("personal_skills"."xp_threshold" >= 0)
);
--> statement-breakpoint
CREATE TABLE "personal_tasks" (
	"task_id" uuid PRIMARY KEY NOT NULL,
	"learning_path_id" uuid NOT NULL,
	"skill_id" uuid NOT NULL,
	"title" text NOT NULL,
	"xp_reward" integer DEFAULT 0 NOT NULL,
	"started_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"archived_at" timestamp with time zone,
	CONSTRAINT "personal_tasks_path_task_key" UNIQUE("learning_path_id","task_id"),
	CONSTRAINT "personal_tasks_xp_reward_nonnegative" CHECK ("personal_tasks"."xp_reward" >= 0)
);
--> statement-breakpoint
CREATE TABLE "personal_workspaces" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_account_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "personal_workspaces_owner_key" UNIQUE("owner_account_id")
);
--> statement-breakpoint
CREATE TABLE "personal_xp_events" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "personal_xp_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"learning_path_id" uuid NOT NULL,
	"task_id" uuid NOT NULL,
	"actor_account_id" uuid NOT NULL,
	"occurred_at" timestamp with time zone NOT NULL,
	"kind" text NOT NULL,
	"cause" text NOT NULL,
	"amount" integer NOT NULL,
	CONSTRAINT "personal_xp_events_kind" CHECK ("personal_xp_events"."kind" IN ('award', 'correction')),
	CONSTRAINT "personal_xp_events_cause" CHECK ("personal_xp_events"."cause" IN ('completion', 'completion_undone', 'reward_change')),
	CONSTRAINT "personal_xp_events_nonzero" CHECK ("personal_xp_events"."amount" <> 0)
);
--> statement-breakpoint
ALTER TABLE "learning_paths" ALTER COLUMN "coach_workspace_id" DROP NOT NULL;
--> statement-breakpoint
ALTER TABLE "learning_paths" ADD COLUMN "personal_workspace_id" uuid;
--> statement-breakpoint
ALTER TABLE "learning_paths" ADD CONSTRAINT "learning_paths_id_personal_workspace_key" UNIQUE("id","personal_workspace_id");
--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_id_learning_path_key" UNIQUE("id","learning_path_id");
--> statement-breakpoint
ALTER TABLE "personal_mastery_events" ADD CONSTRAINT "personal_mastery_events_actor_account_id_accounts_id_fk" FOREIGN KEY ("actor_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_mastery_events" ADD CONSTRAINT "personal_mastery_events_learning_path_id_skill_id_personal_skills_learning_path_id_skill_id_fk" FOREIGN KEY ("learning_path_id","skill_id") REFERENCES "public"."personal_skills"("learning_path_id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_override_records" ADD CONSTRAINT "personal_override_records_actor_account_id_accounts_id_fk" FOREIGN KEY ("actor_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_override_records" ADD CONSTRAINT "personal_override_records_learning_path_id_skill_id_personal_skills_learning_path_id_skill_id_fk" FOREIGN KEY ("learning_path_id","skill_id") REFERENCES "public"."personal_skills"("learning_path_id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_prerequisites" ADD CONSTRAINT "personal_prerequisites_source_fk" FOREIGN KEY ("learning_path_id","prerequisite_skill_id") REFERENCES "public"."personal_skills"("learning_path_id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_prerequisites" ADD CONSTRAINT "personal_prerequisites_target_fk" FOREIGN KEY ("learning_path_id","skill_id") REFERENCES "public"."personal_skills"("learning_path_id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_skills" ADD CONSTRAINT "personal_skills_skill_id_learning_path_id_skills_id_learning_path_id_fk" FOREIGN KEY ("skill_id","learning_path_id") REFERENCES "public"."skills"("id","learning_path_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_skills" ADD CONSTRAINT "personal_skills_learning_path_id_personal_workspace_id_learning_paths_id_personal_workspace_id_fk" FOREIGN KEY ("learning_path_id","personal_workspace_id") REFERENCES "public"."learning_paths"("id","personal_workspace_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_tasks" ADD CONSTRAINT "personal_tasks_task_id_skill_id_tasks_id_skill_id_fk" FOREIGN KEY ("task_id","skill_id") REFERENCES "public"."tasks"("id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_tasks" ADD CONSTRAINT "personal_tasks_learning_path_id_skill_id_personal_skills_learning_path_id_skill_id_fk" FOREIGN KEY ("learning_path_id","skill_id") REFERENCES "public"."personal_skills"("learning_path_id","skill_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_workspaces" ADD CONSTRAINT "personal_workspaces_owner_account_id_accounts_id_fk" FOREIGN KEY ("owner_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_xp_events" ADD CONSTRAINT "personal_xp_events_actor_account_id_accounts_id_fk" FOREIGN KEY ("actor_account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "personal_xp_events" ADD CONSTRAINT "personal_xp_events_learning_path_id_task_id_personal_tasks_learning_path_id_task_id_fk" FOREIGN KEY ("learning_path_id","task_id") REFERENCES "public"."personal_tasks"("learning_path_id","task_id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "learning_paths" ADD CONSTRAINT "learning_paths_personal_workspace_id_personal_workspaces_id_fk" FOREIGN KEY ("personal_workspace_id") REFERENCES "public"."personal_workspaces"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
ALTER TABLE "learning_paths" ADD CONSTRAINT "learning_paths_one_workspace" CHECK (num_nonnulls("learning_paths"."coach_workspace_id", "learning_paths"."personal_workspace_id") = 1);
--> statement-breakpoint
CREATE FUNCTION protect_personal_history_record() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'Personal learning history records are immutable';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER personal_xp_events_immutable BEFORE UPDATE OR DELETE ON personal_xp_events
FOR EACH ROW EXECUTE FUNCTION protect_personal_history_record();
--> statement-breakpoint
CREATE TRIGGER personal_mastery_events_immutable BEFORE UPDATE OR DELETE ON personal_mastery_events
FOR EACH ROW EXECUTE FUNCTION protect_personal_history_record();
--> statement-breakpoint
CREATE TRIGGER personal_override_records_immutable BEFORE UPDATE OR DELETE ON personal_override_records
FOR EACH ROW EXECUTE FUNCTION protect_personal_history_record();