/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as EnrollmentsEnrollmentIdRouteImport } from './routes/enrollments.$enrollmentId'
import { Route as InvitationsInvitationIdRouteImport } from './routes/invitations.$invitationId'
import { Route as PathsPathIdRouteImport } from './routes/paths.$pathId'
import { Route as WorkspacesWorkspaceIdRouteImport } from './routes/workspaces.$workspaceId'
import { Route as CoachPathsPathIdRouteImport } from './routes/coach.paths.$pathId'
import { Route as CoachVersionsVersionIdRouteImport } from './routes/coach.versions.$versionId'
import { Route as CoachWorkspacesWorkspaceIdRouteImport } from './routes/coach.workspaces.$workspaceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentsEnrollmentIdRoute = EnrollmentsEnrollmentIdRouteImport.update({
  id: '/enrollments/$enrollmentId',
  path: '/enrollments/$enrollmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsInvitationIdRoute = InvitationsInvitationIdRouteImport.update({
  id: '/invitations/$invitationId',
  path: '/invitations/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsPathIdRoute = PathsPathIdRouteImport.update({
  id: '/paths/$pathId',
  path: '/paths/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceIdRoute = WorkspacesWorkspaceIdRouteImport.update({
  id: '/workspaces/$workspaceId',
  path: '/workspaces/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachPathsPathIdRoute = CoachPathsPathIdRouteImport.update({
  id: '/coach/paths/$pathId',
  path: '/coach/paths/$pathId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachVersionsVersionIdRoute = CoachVersionsVersionIdRouteImport.update({
  id: '/coach/versions/$versionId',
  path: '/coach/versions/$versionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachWorkspacesWorkspaceIdRoute =
  CoachWorkspacesWorkspaceIdRouteImport.update({
    id: '/coach/workspaces/$workspaceId',
    path: '/coach/workspaces/$workspaceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/learning': typeof LearningRoute
  '/api/$': typeof ApiSplatRoute
  '/enrollments/$enrollmentId': typeof EnrollmentsEnrollmentIdRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/paths/$pathId': typeof CoachPathsPathIdRoute
  '/coach/versions/$versionId': typeof CoachVersionsVersionIdRoute
  '/coach/workspaces/$workspaceId': typeof CoachWorkspacesWorkspaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/learning': typeof LearningRoute
  '/api/$': typeof ApiSplatRoute
  '/enrollments/$enrollmentId': typeof EnrollmentsEnrollmentIdRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coach': typeof CoachIndexRoute
  '/coach/paths/$pathId': typeof CoachPathsPathIdRoute
  '/coach/versions/$versionId': typeof CoachVersionsVersionIdRoute
  '/coach/workspaces/$workspaceId': typeof CoachWorkspacesWorkspaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/learning': typeof LearningRoute
  '/api/$': typeof ApiSplatRoute
  '/enrollments/$enrollmentId': typeof EnrollmentsEnrollmentIdRoute
  '/invitations/$invitationId': typeof InvitationsInvitationIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/workspaces/$workspaceId': typeof WorkspacesWorkspaceIdRoute
  '/coach/': typeof CoachIndexRoute
  '/coach/paths/$pathId': typeof CoachPathsPathIdRoute
  '/coach/versions/$versionId': typeof CoachVersionsVersionIdRoute
  '/coach/workspaces/$workspaceId': typeof CoachWorkspacesWorkspaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/learning'
    | '/api/$'
    | '/enrollments/$enrollmentId'
    | '/invitations/$invitationId'
    | '/paths/$pathId'
    | '/workspaces/$workspaceId'
    | '/coach/'
    | '/coach/paths/$pathId'
    | '/coach/versions/$versionId'
    | '/coach/workspaces/$workspaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/editor'
    | '/learning'
    | '/api/$'
    | '/enrollments/$enrollmentId'
    | '/invitations/$invitationId'
    | '/paths/$pathId'
    | '/workspaces/$workspaceId'
    | '/coach'
    | '/coach/paths/$pathId'
    | '/coach/versions/$versionId'
    | '/coach/workspaces/$workspaceId'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/learning'
    | '/api/$'
    | '/enrollments/$enrollmentId'
    | '/invitations/$invitationId'
    | '/paths/$pathId'
    | '/workspaces/$workspaceId'
    | '/coach/'
    | '/coach/paths/$pathId'
    | '/coach/versions/$versionId'
    | '/coach/workspaces/$workspaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  LearningRoute: typeof LearningRoute
  ApiSplatRoute: typeof ApiSplatRoute
  EnrollmentsEnrollmentIdRoute: typeof EnrollmentsEnrollmentIdRoute
  InvitationsInvitationIdRoute: typeof InvitationsInvitationIdRoute
  PathsPathIdRoute: typeof PathsPathIdRoute
  WorkspacesWorkspaceIdRoute: typeof WorkspacesWorkspaceIdRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachPathsPathIdRoute: typeof CoachPathsPathIdRoute
  CoachVersionsVersionIdRoute: typeof CoachVersionsVersionIdRoute
  CoachWorkspacesWorkspaceIdRoute: typeof CoachWorkspacesWorkspaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollments/$enrollmentId': {
      id: '/enrollments/$enrollmentId'
      path: '/enrollments/$enrollmentId'
      fullPath: '/enrollments/$enrollmentId'
      preLoaderRoute: typeof EnrollmentsEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$invitationId': {
      id: '/invitations/$invitationId'
      path: '/invitations/$invitationId'
      fullPath: '/invitations/$invitationId'
      preLoaderRoute: typeof InvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths/$pathId': {
      id: '/paths/$pathId'
      path: '/paths/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof PathsPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceId': {
      id: '/workspaces/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof WorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/paths/$pathId': {
      id: '/coach/paths/$pathId'
      path: '/coach/paths/$pathId'
      fullPath: '/coach/paths/$pathId'
      preLoaderRoute: typeof CoachPathsPathIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/versions/$versionId': {
      id: '/coach/versions/$versionId'
      path: '/coach/versions/$versionId'
      fullPath: '/coach/versions/$versionId'
      preLoaderRoute: typeof CoachVersionsVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/workspaces/$workspaceId': {
      id: '/coach/workspaces/$workspaceId'
      path: '/coach/workspaces/$workspaceId'
      fullPath: '/coach/workspaces/$workspaceId'
      preLoaderRoute: typeof CoachWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  LearningRoute: LearningRoute,
  ApiSplatRoute: ApiSplatRoute,
  EnrollmentsEnrollmentIdRoute: EnrollmentsEnrollmentIdRoute,
  InvitationsInvitationIdRoute: InvitationsInvitationIdRoute,
  PathsPathIdRoute: PathsPathIdRoute,
  WorkspacesWorkspaceIdRoute: WorkspacesWorkspaceIdRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachPathsPathIdRoute: CoachPathsPathIdRoute,
  CoachVersionsVersionIdRoute: CoachVersionsVersionIdRoute,
  CoachWorkspacesWorkspaceIdRoute: CoachWorkspacesWorkspaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
